package com.company.Start;
import java.awt.*;
import java.util.Date;
import java.util.Arrays;
import java.text.NumberFormat;
import java.util.Scanner;

public class Start {
    public static void main(String[] args) {
        byte a = 30;
        Date n = new Date();
        System.out.println(n);
        byte x = 1;
        byte y = x;
        x = 2;
        System.out.println(y);
        Point p1 = new Point(1, 1);
        Point p2 = p1;
        p1.x = 2;
        System.out.println(p2);
        String s = "Hello World" + "!!!";
        System.out.println(s);
        System.out.println(s.endsWith("!!!"));
        System.out.println(s.startsWith("!"));
        System.out.println(s.length());
        System.out.println(s.indexOf("e"));
        System.out.println(s.replace("!", "@"));
        System.out.println(s.toLowerCase());
        int[] A = new int[5];
        A[0] = 1;
        A[1] = 2;
        System.out.println(Arrays.toString(A));
        int[] A1 = {2, 5, 8};
        System.out.println(A1.length);
        Arrays.sort(A1);
        System.out.println(Arrays.toString(A1));
        int[][] A2 = new int[3][3];
        A2[0][0] = 1;
        System.out.println(Arrays.deepToString(A2));
        String s1 = "1";
        int s2 = Integer.parseInt(s1);
        System.out.println(s2);
        String s3 = "1.1";
        double s4 = Double.parseDouble(s3);
        System.out.println(s4);
        int r = Math.round(1.5F);
        System.out.println(r);
        int r1 = (int) Math.ceil(0.01F);
        System.out.println(r1);
        int r2 = (int) Math.floor(2.9F);
        System.out.println(r2);
        int r3 = Math.min(2, 4);
        System.out.println(r3);
        double r4 = Math.round(Math.random() * 100);
        System.out.println(r4);
        int r5 = (int) Math.round(Math.random() * 100);
        System.out.println(r5);
        NumberFormat c = NumberFormat.getCurrencyInstance();
        String c1 = c.format(123456.987);
        NumberFormat c2 = NumberFormat.getPercentInstance();
        String c3 = c2.format(0.3);
        System.out.println(c1 + c3);
        Scanner scanner = new Scanner(System.in);
        System.out.print("Age: ");
        byte b = scanner.nextByte();
        System.out.println("Your age is " + b);
        System.out.print("Your name: ");
        String b1 = scanner.next();
        System.out.println("Your name is " + b1);
        System.out.print("Your full name: ");
        String b3 = scanner.nextLine().trim(); // doesn`t work, only .next
        System.out.println("Your full name is " + b3);
        int xa = 1;
        int ya = 2;
        System.out.println(xa == ya);
        System.out.println(xa > ya);
        System.out.println(xa < ya);
        boolean h = false;
        boolean h1 = true;
        boolean h2 = false;
        boolean h3 = ((h||h1 )&&!h2);
        System.out.println(h3);
    }
}
